### PR TITLE
Fix #1988 Allow timezone_type, timezone, date to be modified before __construct

### LINKED ISSUE #1988: InvalidArgumentException : Unknown setter 'date’
Hello,

I have an issue with Carbon dates that are serialised through [GitHub - opis/closure: Serialize closures (anonymous functions)](https://github.com/opis/closure)

Laravel version: 6.11.0
Carbon version: 2.28.0
PHP version:  7.3.10
Opis/Closure version: 3.5.1

The problem seems to occur after upgrading to Laravel 6 and therefor upgraded from Carbon 1 to Carbon 2.

I wasn’t sure if this belongs to the Carbon or Opis issues. So I’ve posted this question on both. I will provide links later.

When a closure is serialized:
```php
return serialize(new SerializableClosure($closure, true));
```

I get this error: `InvalidArgumentException : Unknown setter 'date’`.

This boils down to `/nesbot/carbon/src/Carbon/Traits/Date.php:1166`.

I’ve googled this issue for some time now and I believe it has got a lot to do with the depreciation of `serializeUsing` on Carbon 2.
As found in issue [Provide an alternative to serializeUsing to Laravel users · Issue #1870 · briannesbitt/Carbon · GitHub](https://github.com/briannesbitt/Carbon/issues/1870). @driesvints

However after reading multiple threats I’m not able to find a solution. I really hope someone can help me steering me to the right direction 🙏.

Thanks!

### PR DESCRIPTION
**Pull request by kylekatarnls**
This allow DateTime-compatible using `(new ReflectionClass(Carbon::class))->newInstanceWithoutConstructor()`

### CODE REVIEW

File: src/Carbon/Traits/Date.php [hunk 1]
```diff
@@ -1155,6 +1161,11 @@ public function set($name, $value = null)
 
                 break;
 
+            case 'date':
```
Comment (sorinsarca) [inline src/Carbon/Traits/Date.php]: For safety reasons, I think this case should be postponed until #1992 is fixed, otherwise there will be the same bug for the `date` property.

Comment (kylekatarnls) [reply src/Carbon/Traits/Date.php]: Yep, indeed it's a first try that shouldn't be there.

**Comment by stefro** [comment]
After commit 0a5ed5a I get `InvalidArgumentException : Unknown setter 'date'` again.

Shouldn't it be (`!$this` -> `$this`):
```php
        if ($this->constructed && in_array($name, ['timezone_type', 'timezone', 'date'])) {
            $this->$name = $value;
            return $this;
        }
```

If I change that, it works fine.

**Comment by kylekatarnls** [comment]
Of course, thanks. Can't explain what the unit test pass. Let's recheck all that.

**Comment by kylekatarnls** [comment]
Oups sorry, I read too fast, nope, it should not be `$this->constructed`, `!$this->constructed` is correct, but as unserialized instances do not trigger __construct, the solution may be to also set the `constructed` property in `__wakeup` as @msarca did in #1994.

**Comment by stefro** [comment]
I've pulled the 8209f88 into my project and unfortunately it gives me the `InvalidArgumentException : Unknown setter 'date'` again.

**Comment by kylekatarnls** [comment]
However this code added is the same process as in opis/closure: https://github.com/briannesbitt/Carbon/pull/1993/commits/638291e402940a002713d6fb5a3a5fe0c03c6ca3#diff-62330e87d38a327cd927526b11a0da6cR104
And this unit test is passing.

@msarca Do you see something that could differ in this unit test from opis/closure unserialization?

> It's the `$this->constructed` part that confuses me. I'll try to go over the code to understand.

It's about enabling the __set feature only once the datetime is initialized (__construct or __wakeup).

So before the construction (`!$this->constructed`), we set the property as a public one (`$this->$name = $value`)

**Comment by stefro** [comment]
Maybe it my poor understanding of this complex piece of code. 
>but as unserialized instances do not trigger __construct, the solution may be to also set the constructed property in __wakeup as @msarca did in #1994.
I get the `$this->constructed = true;` in `Serialization.php` since you've put it in the `__wakeup()` method.

But the ` $this->constructed = true;` in `Creator.php (line 79) confuses me. When I comment it out, no exceptions are thrown. When I leave it in I still get `InvalidArgumentException : Unknown setter 'date'`.

**Comment by kylekatarnls** [comment]
Yes this error is gone and the __set is broken, it's like you would simply remove the whole `__set` and so breaking many feature.

If you still have the error, it would mean opis/closure set the `date` property after the date is yet initialized.

**Comment by kylekatarnls** [comment]
I just checked to be sure, and using `$this->constructed` instead of `!$this->constructed` breaks 37 other unit tests :( So nope, not a solution.

**Comment by kylekatarnls** [comment]
Let's make some dreams of it, solution will raise up tomorrow.

**Comment by msarca** [comment]
> @msarca Do you see something that could differ in this unit test from opis/closure unserialization?

Yep. We also iterate over the properties of the ancestors using a while loop `$while($reflection = $reflection->getParentClass())`

**Comment by stefro** [comment]
>Let's make some dreams of it, solution will raise up tomorrow.

Great idea! I'll be back in the morning. Thanks for your effort today, all of you. Are any of you guys at Laracon EU this year? I feel like I need to buy you some beers :-)

**Comment by msarca** [comment]
I've updated my PR and came up with a solution that works. Take a look guys and give me some feedback tomorrow.

**Comment by stefro** [comment]
I can conform that 5ddb5b85 in the PR from @msarca works! Awesome!!!!! 🎉

**Comment by kylekatarnls** [comment]
Awesome, we're almost done, we just have 1 unit test that fail on PHP 7.4:
https://travis-ci.org/briannesbitt/Carbon/jobs/638654028#L463

I will check

**Comment by stefro** [comment]
I’m not at home right now. I will check as soon as I’m back to confirm.

**Comment by kylekatarnls** [comment]
Just one more thing, the ID also need to be updated when cloned.
