### PR TITLE
Use static reflection to determine whether class is `CarbonInstance`

### LINKED ISSUE #2703: PHPStan extension loads analyzed code
Hello,

I encountered an issue with this library's PHPStan extension:

Carbon version: 2.63.0
- Additionally `phpstan/extension-installer` must be installed, or Carbon's PHPStan extension must have been included manually

PHP version: 8.1.10

I have the following (simplified) code snippet:

```php
final class Foo
{
    public function __construct(
        public readonly string $bar,
    ) {
    }
}

(new Foo())->baz();
```

I expected to get:

No error. Even though the code is invalid (the class instantiation is missing a required parameter), this should never be an issue for PHPStan as it uses static analysis and doesn't actually run any code it analyses.

But I actually get:

```text
Uncaught ArgumentCountError: Too few arguments to function App\Foo::__construct(), 0 passed in /Users/me/Sites/my-project/tests/app/Foo.php on line 13 and exactly 1 expected in /Users/me/Sites/my-project/tests/app/Foo.php:7
#0 /Users/me/Sites/my-project/tests/app/Foo.php(13): App\Foo->__construct()
#1 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/vendor/composer/ClassLoader.php(571): include('/Users/me...')
#2 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/me...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Foo')
#4 /Users/me/Sites/my-project/vendor/nesbot/carbon/src/Carbon/PHPStan/MacroScanner.php(33): is_a('App\\Foo', 'Carbon\\CarbonIn...', true)
#5 /Users/me/Sites/my-project/vendor/nesbot/carbon/src/Carbon/PHPStan/MacroExtension.php(53): Carbon\PHPStan\MacroScanner->hasMethod('App\\Foo', 'baz')
#6 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php(422): Carbon\PHPStan\MacroExtension->hasMethod(Object(PHPStan\Reflection\ClassReflection), 'baz')
#7 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php(488): PHPStan\Reflection\ClassReflection->hasMethod('baz')
#8 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Methods/CallToMethodStatementWithoutSideEffectsRule.php(55): PHPStan\Type\ObjectType->hasMethod('baz')
#9 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(106): PHPStan\Rules\Methods\CallToMethodStatementWithoutSideEffectsRule->processNode(Object(PhpParser\Node\Stmt\Expression), Object(PHPStan\Analyser\MutatingScope))
#10 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(412): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Stmt\Expression), Object(PHPStan\Analyser\MutatingScope))
#11 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(357): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Expression), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#12 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(568): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#13 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(327): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#14 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(175): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#15 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/Analyser.php(71): PHPStan\Analyser\FileAnalyser->analyseFile('/Users/me...', Array, Object(PHPStan\Rules\LazyRegistry), Object(PHPStan\Collectors\Registry), NULL)
#16 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyserRunner.php(63): PHPStan\Analyser\Analyser->analyse(Array, Object(Closure), NULL, true, Array)
#17 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(207): PHPStan\Command\AnalyserRunner->runAnalyser(Array, Array, Object(Closure), NULL, true, true, '/Users/me...', NULL, NULL, Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput))
#18 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(101): PHPStan\Command\AnalyseApplication->runAnalyser(Array, Array, true, '/Users/me...', Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput))
#19 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(168): PHPStan\Command\AnalyseApplication->analyse(Array, false, Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), false, true, '/Users/me...', Array, Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput))
#20 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute(Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Output\ConsoleOutput))
#21 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(868): _PHPStan_582a9cb8b\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Output\ConsoleOutput))
#22 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(259): _PHPStan_582a9cb8b\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Output\ConsoleOutput))
#23 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_582a9cb8b\Symfony\Component\Console\Application->doRun(Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_582a9cb8b\Symfony\Component\Console\Output\ConsoleOutput))
#24 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(124): _PHPStan_582a9cb8b\Symfony\Component\Console\Application->run()
#25 phar:///Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(125): _PHPStan_582a9cb8b\{closure}()
#26 /Users/me/Sites/my-project/vendor/phpstan/phpstan/phpstan(8): require('phar:///Users/c...')
#27 /Users/me/Sites/my-project/vendor/bin/phpstan(120): include('/Users/me...')
#28 {main}
```

What is happening?

PHPStan is trying to figure out what `Foo::baz()` is, in doing so it calls Carbon's extension. The extension has a class called `MacroScanner` which performs a `is_a()` check on the class string. Because the class isn't loaded at this point (PHPStan doesn't normally load any classes it analyses), PHP triggers Composer's autoloader and 💥 the broken code is loaded.

Why is this an issue?

An argument could be made that the crash is ok, because the code was invalid. But the problem is actually the fact that this extension loads any class it comes into contact with into memory (which is not very static analysis-y). Depending on project size and the amount of magic going on in the code this extension can get called a lot and every time it encounters a new class it is erroneously loaded into memory.

How do we fix this?

It might not be possible to make the PHPStan extension fully static, because it deals with macros which are typically only available at runtime. However changing the `is_a()` check to an identical check using PHPStan's static reflection would mostly solve the issue. Most classes won't pass this check, making the `MacroScanner` return early. The only classes that would be loaded into memory would be implementations of `CarbonInterface`.

### PR DESCRIPTION
**Pull request by axlon**
Fixes #2703

### CODE REVIEW

**Comment by kylekatarnls** [comment]
It needs the tests to be aligned. Also I'll need to check that the dependency injection is working as expected in all the PHPStan versions we need to support.

**Comment by axlon** [comment]
Am working on fixing the tests

**Comment by axlon** [comment]
From what I can tell the remaining test failures are unrelated to this PR

File: src/Carbon/PHPStan/MacroScanner.php [hunk 1]
```diff
@@ -29,8 +45,16 @@ final class MacroScanner
...
+        $classReflection = $this->reflectionProvider->getClass($className);
+
+        if (
+            $classReflection->getName() !== CarbonInterface::class &&
+            !$classReflection->isSubclassOf(CarbonInterface::class)
+        ) {
+            return false;
+        }
+
+        return \is_callable([$className, 'hasMacro']) &&
```
Comment (kylekatarnls) [inline src/Carbon/PHPStan/MacroScanner.php:57]: This should probably be `$classReflection->hasMethod('hasMacro')` but I will first check and merge this and check in a next step if this part can also be static.

Comment (axlon) [reply src/Carbon/PHPStan/MacroScanner.php:57]: I think the `is_callable()` check could probably be removed, because `hasMacro` is defined on `CarbonInterface`. So we're already sure its callable (unless I'm missing something)

**Comment by kylekatarnls** [comment]
Tested compatible with PHPStan:
1.9.2 ✔️
1.8.0 ✔️
1.7.14 ✔️
0.12.99 ✔️

File: src/Carbon/PHPStan/MacroScanner.php (hunk 1 above)
Comment (kylekatarnls) [reply src/Carbon/PHPStan/MacroScanner.php:57]: It can be an old or modified version of `CarbonInterface` so it does not have `hasMacro` but yeah it's very unlikely.
